@echo off
set DJANGO_SETTINGS_MODULE=settings.local_settings
set DJANGO_DB_NAME=studyhub
set DJANGO_DB_USER=studyhub
set DJANGO_DB_PASS=
set DJANGO_SECRET=
set DJANGO_DB_TYPE=django.db.backends.postgresql
set DJANGO_DB_PORT=5432
set MYSQL_PROBLEM_TYPE_HOST=127.0.0.1
set MYSQL_PROBLEM_TYPE_USER=studyhub
set MYSQL_PROBLEM_TYPE_USER_PASSWORD=