@echo off
set DJANGO_SETTINGS_MODULE=settings.local_settings
set DJANGO_DB_NAME=studyhub
set DJANGO_DB_USER=studyhub
set DJANGO_DB_PASS=
set DJANGO_SECRET=
set DJANGO_DB_TYPE=django.db.backends.postgresql
set DJANGO_DB_PORT=5432
set MYSQL_PROBLEM_TYPE_HOST=127.0.0.1
set MYSQL_PROBLEM_TYPE_USER=studyhub
set MYSQL_PROBLEM_TYPE_USER_PASSWORD=
set RUN_CODE_SERVER_ACCESS_TOKEN=
set RUN_CODE_SERVER_URL=http://00.00.00.00:8088/run;
set CELERY_BROKER_URL=amqp://myuser:mypassword@localhost:5672/myvhost